#--------------------------------------------------------------------
############################# RL config #############################
#--------------------------------------------------------------------
# only for DDPG, TD3 or SAC

#------------- parameters common to DDPG, TD3 and SAC ---------------
GAME : "STARCCMexternalfiles"

MEMORY_CAPACITY : 500000        # for the Replay Memory
BATCH_SIZE : 64
GAMMA : 0.99                    # discount factor
TAU : 0.005                     # update parameter of the target network

ACTION_SIGMA : 0.0              # environment noise ([0 --> 0; 1 --> max_pitch])

MAX_EPISODES : 100             # number of training episodes
MAX_STEPS : 150                 # max steps per episode
PRE_FILL_EPISODES : 8           # number of pre-filling episodes

# saving and plotting parameters
FREQ_PLOT : 100                 # frequency at which plots are updated
FREQ_EVAL : 10                  # evaluation frequency
FREQ_SAVE : "best"              # frequency at which the models are saved (or the best model is saved)


#-------------- parameters used only by DDPG and TD3 ----------------
HIDDEN_LAYERS : [32, 32]        # NN size
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001

EXPLO_SIGMA : 0.05              # exploration noise


#------------------- parameters used only by TD3 --------------------
# next 2 parameters are set according to the founding paper
UPDATE_SIGMA : 0.2
UPDATE_CLIP : 0.5


#------------------- parameters used only by SAC --------------------
HIDDEN_VALUE_LAYERS : [32, 32]  # NN size
HIDDEN_Q_LAYERS : [32, 32]      # NN size
HIDDEN_PI_LAYERS : [32, 32]     # NN size

VALUE_LR : 0.001
SOFTQ_LR : 0.001
ACTOR_LR : 0.001

AUTO_ALPHA : True
ALPHA_LR : 0.001


#--------------------------------------------------------------------
############################ CFD config #############################
#--------------------------------------------------------------------
CFD_ITERATIONS : 1              # number of CFD iterations between two control iterations !!! careful, to set in macro_external.java too !!!
DELTA_TIME : 0.00002            # time step !!! careful, to set in the CFD.sim too !!!

# initial position
XA : 0.0
YA : 0.0
UA : -10.0                      # !!! careful, to set in the CFD and load corresponding init !!!
VA : 0.0

# target position
BTYPE : "random"                # target position type let it set to random
DISTANCE_RANGE : [0.015, 0.021] # definition of B domain - distance
ANGLE_RANGE : [-8., 8.]         # definition of B domain - angle
XB : -0.02                      # only used if BTYPE or BTYPE_EVAL is "fixed"
YB : 0.002                      # only used if BTYPE or BTYPE_EVAL is "fixed"

# target position definition for evaluation
BTYPE_EVAL : "batch"
# list of B positions for evaluation (only used if BTYPE_EVAL is batch)
B_BATCH : [[-0.0148540, -0.0020876], [-0.0207956, -0.0029226], [-0.0148540, 0.0020876], [-0.0207956, 0.0029226]]

# some parameters for the control problem
MAX_PITCHRATE : 500.            # maximum allowed pitch rate
REWARD_TYPE : "dense"           # choose between dense and sparse
